[project]
authors = ["Tobias Fischer <info@tobiasfischer.info>"]
channels = ["conda-forge"]
name = "pyslam"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12"  # Replace "12" with the specific CUDA version you intend to use

[tasks]

[dependencies]
absl-py = "*"
astor = "*"
cycler = "*"
decorator = "*"
gast = "*"
google-pasta = "*"
grpcio = "*"
h5py = "*"
imageio = "*"
kornia = "*"
keras = "*"
kiwisolver = "*"
markdown = "*"
matplotlib = "*"
networkx = "*"
ordered-set = "*"
pillow = "*"
protobuf = "*"
psutil = "*"
pybind11 = "*"
eigen = "*"
pygame = "*"
compilers = "*"
cmake = "<4"
pip = "*"
pyopengl = "*"
pyopenssl = "*"
pyparsing = "*"
python-dateutil = "*"
pyyaml = "*"
scipy = "*"
scikit-image = "*"
seaborn = "*"
six = "*"
sklearn-pandas = "*"
tensorflow = "*"
termcolor = "*"
tqdm = "*"
werkzeug = "*"
wrapt = "*"
yacs = "*"
opencv = "*"
wget = "*"
doxygen = "*"
glew = "*"
pkg-config = "*"
suitesparse = "*"
zlib = "*"
bzip2 = "*"
rsync = "*"
readline = "*"
libboost-devel = "*"
flann = "*"
catch2 = "*"
gdown = "*"
x265 = "*"
libheif = "*"
gtk2 = "*"
hdf5 = "*"
tmux = "*"
nano = "*"
setuptools = "*"
wheel = "*"
pyqt = "*"
pytorch-gpu = "*"
torchvision = "*"
ujson = "*"
tensorflow-hub = "*"
einops = "*"
pyflann = "*"
faiss = "*"
trimesh = "*"
jax = "*"
munch = "*"
wandb = "*"
plyfile = "*"
torchmetrics = "*"
imgviz = "*"
pyglm = "*"
lpips = "*"
rich = "*"
ruff = "*"
gradio = "*"
pytorch3d = "*"
libgl-devel = "*"
libopengl-devel = "*"
libegl-devel = "*"
libglx-devel = "*"
cython = "0.29.*"
python = "3.12.*"
cuda-compiler = "12.*"
metis = "*"
rerun-sdk = "*"
rattler-build = "*"
fast-pytorch-kmeans = "*"
timm = "*"
pillow-heif = "*"
evo = "*"
quaternion = "*"
open3d = "*"
gtsam = "*"
tbb = ">=2021.13.0,<2022"
tbb-devel = ">=2021.13.0,<2022"
pyqtgraph = "*"



